# 02_Demultiplex, subset singlets, add quality features

```{r 02_libraries}
suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
})
```

## Functions
```{r 02_functions}
# Demultiplex
demultiplex <- function(seu) {
  seu_demuxed <- Seurat::MULTIseqDemux(
    seu,
    assay = "HTO",
    quantile = 0.7,
    autoThresh = TRUE,
    maxiter = 5,
    qrange = seq(from = 0.1, to = 0.9, by = 0.05),
    verbose = TRUE
  )
  table(seu_demuxed$MULTI_ID)

  return(seu_demuxed)
}
# Subset singlets
subset_singlets <- function(seu_demuxed) {
  seu_singlet <- subset(seu_demuxed, idents = c("tumor", "csf"))
  seu_negative <- subset(seu_demuxed, idents = "Negative")

  return(list("seu_singlet" = seu_singlet, "seu_negative" = seu_negative))
}
# Add quality features to singets
add_quality_features <- function(seu) {
  seu <- Seurat::PercentageFeatureSet(
    seu,
    pattern = "^RP[SL]",
    col.name = "percent_ribo"
  )
  seu <- Seurat::PercentageFeatureSet(
    seu,
    pattern = "^MT-",
    col.name = "percent_mito"
  )
  seu <- Seurat::PercentageFeatureSet(
    seu,
    pattern = "^HB[^(P)]",
    col.name = "percent_hemoglob"
  )
  seu[["log10GenesPerUmi"]] <-
    log10(seu$nFeature_RNA) / log10(seu$nCount_RNA)

  return(seu)
}
# Add cell cycle scoring
add_cell_cycle_scoring <- function(seu_singlet) {
  s_genes <- Seurat::cc.genes$s.genes
  g2m_genes <- Seurat::cc.genes$g2m.genes

  seu_singlet <- Seurat::CellCycleScoring(
    seu_singlet,
    s.features = s_genes,
    g2m.features = g2m_genes,
    set.ident = TRUE
  )

  return(seu_singlet)
}
```

## Run pipeline
```{r 02_pipeline}
set.seed(123)

seu_singlet_negative_list <- demultiplex(seu_raw_object) |>
  subset_singlets()

seu_singlet_b4_q_filtering <- add_quality_features(
  seu_singlet_negative_list$seu_singlet
) |>
  add_cell_cycle_scoring()
```

