# 03_Normalize, Visualize before quality filtering

```{r 03_libraries}
suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(clustree)
  library(reticulate) # load packages required by leiden algo
  reticulate::use_condaenv("/mnt/sda4/conda/envs/R")
  library(viridis) # colors
  options(future.globals.maxSize = 3.0 * 1e9) # 3GB
})
```

## Imports
```{r 03_imports}
source("/mnt/sda4/singleCell_LAB/HitGlio_sample1-test/scripts/functions.R")
source("/mnt/sda4/singleCell_LAB/HitGlio_sample1-test/scripts/00_Global_vars.R")
```

## Functions
```{r 03_functions}
```

## Run pipeline
```{r 03_pipeline}
set.seed(123)

seu_singlet_b4_q_filt_norm <- seu_normalize_var_scale_pca(
  seu_singlet_b4_q_filtering,
  normalize = "log",
  cluster.name = "cluster.log",
  pca.reduction.name = "pca",
  umap.reduction.name = "umap.log",
  dims = 1:30,
  k.param = 20,
  algorithm = 4,
  resolution = 0.5,
  group.singletons = TRUE
)
viz_quality(
  seu_singlet_b4_q_filt_norm,
  assay = "RNA", q_features,
  reduction = "umap.log", gr_by_features
)
plot_scatter(seu_singlet_b4_q_filt_norm)
ElbowPlot(seu_singlet_b4_q_filt_norm, ndims = 40)

# Subset cells based on quality assesment
seu_singlet_q_filt_norm <- subset(
  seu_singlet_b4_q_filt_norm,
  subset = nFeature_RNA > 200 &
    nFeature_RNA < 7000 &
    nCount_RNA < 50000 &
    nCount_RNA > 500 &
    percent_mito < 8 &
    nCount_ADT < quantile(seu_singlet_b4_q_filt_norm$nCount_ADT, 0.99)
)
viz_quality(
  seu_singlet_q_filt_norm,
  assay = "RNA", q_features,
  reduction = "umap.log", gr_by_features
)
plot_scatter(seu_singlet_q_filt_norm)
```
