# 04_Remove Doublets

```{r 04_libraries}
suppressPackageStartupMessages({
  library(Seurat)
  library(DropletUtils)
  library(ggplot2)
  library(Matrix)
  library(dplyr)
  library(reticulate) # load packages required by leiden algo
  reticulate::use_condaenv("/mnt/sda4/conda/envs/R")
  library(viridis) # colors
  library(DoubletFinder)
  options(future.globals.maxSize = 3.0 * 1e9) # 3GB
})
```

## Imports
```{r}
source("/mnt/sda4/singleCell_LAB/HitGlio_sample1-test/scripts/functions.R")
source("/mnt/sda4/singleCell_LAB/HitGlio_sample1-test/scripts/00_Global_vars.R")
```

## Functions
```{r 04_functions}
remove_doublets_w_dfinder <- function(seu_singlet) {
  homotypic_prop <- DoubletFinder::modelHomotypic(seu_singlet$cluster.sct)
  nExp_poi <- round(0.075 * nrow(seu_singlet)) # estimate ~7.5% doublets
  nExp_poi_adj <- round(nExp_poi * (1 - homotypic_prop))

  seu_singlet <- DoubletFinder::doubletFinder(
    seu_singlet,
    PCs = 1:10,
    pN = 0.25,
    pK = 0.09,
    nExp = nExp_poi_adj,
    reuse.pANN = FALSE,
    sct = TRUE
  )
  colnames(seu_singlet@meta.data)
  head(seu_singlet@meta.data)

  return(seu_singlet)
}
```

## Run pipeline
```{r 04_pipeline}
set.seed(123)

# normalize after quality subsetting (SCT)
seu_singlet <- seu_normalize_var_scale_pca(
  seu_singlet_q_filt_norm, # form 03_
  normalize = "sct",
  cluster.name = "cluster.sct",
  pca.reduction.name = "pca.sct",
  umap.reduction.name = "umap.sct",
  dims = 1:10, # change to 10 in case of removing doublets
  k.param = 20,
  algorithm = 4,
  resolution = 0.2, # res probably could be lower, like 0.2
  group.singletons = TRUE
)
DefaultAssay(seu_singlet) <- "SCT"

# remove doublets
seu_singlet <- remove_doublets_w_dfinder(seu_singlet)

# subset tru singlets
seu_singlet <- subset(
  seu_singlet,
  subset = DF.classifications_0.25_0.09_1657 == "Singlet"
)

# normalize and viz gex and recluster after dfinder
seu_singlet <- seu_normalize_var_scale_pca(
  seu_singlet,
  normalize = "sct",
  cluster.name = "cluster.sct",
  pca.reduction.name = "pca.sct",
  umap.reduction.name = "umap.sct",
  dims = 1:20,
  k.param = 30,
  algorithm = 4,
  resolution = 0.8,
  group.singletons = FALSE
)
viz_quality(
  seu_singlet,
  assay = "SCT", t_quality,
  reduction = "umap.sct", gr_by_features_sct
)
seu_dittoDotPlot(
  seu_singlet,
  vars = t_quality,
  group.by = "cluster.sct"
)

# normalize ADT with CLR
DefaultAssay(seu_singlet) <- "ADT"
seu_singlet <- NormalizeData(
  seu_singlet,
  assay = "ADT",
  normalization.method = "CLR"
)
viz_quality(
  seu_singlet,
  assay = "ADT", c(t_adt_quality, isotype_controls),
  reduction = "umap.sct", gr_by_features_sct
)
seu_dittoDotPlot(
  seu_singlet,
  vars = t_adt_quality,
  group.by = "cluster.sct"
)
```






